alphavantage:
  url: http://localhost:9090
  timeout: 3

worldtradingdata:
  url: https://api.worldtradingdata.com

# reference: https://resilience4j.readme.io/docs/circuitbreaker
resilience4j.circuitbreaker:
  instances:
    stockPriceCircuitBreaker:
      minimumNumberOfCalls: 5
      registerHealthIndicator: true
      failureRateThreshold: 50
      waitDurationInOpenState: 60000
      slowCallDurationThreshold: 2
      slowCallRateThreshold: 50



logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"
