spring:
  application:
    name: chaos-engineering-demo
  profiles:
    active: chaos-monkey

alphavantage:
  url: https://www.alphavantage.co
  timeout: 3

worldtradingdata:
  url: https://api.worldtradingdata.com

# reference: https://resilience4j.readme.io/docs/circuitbreaker
resilience4j.circuitbreaker:
  instances:
    stockPriceCircuitBreaker:
      minimumNumberOfCalls: 5
      registerHealthIndicator: true
      failureRateThreshold: 50
      waitDurationInOpenState: 20000
      slowCallDurationThreshold: 2
      slowCallRateThreshold: 50

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"



chaos:
  monkey:
    enabled: true
    watcher:
      component: true
      controller: true
      repository: true
      rest-controller: true
      service: true
    assaults:
      level: 3
      latency-active: true
      latency-range-end: 10000
      latency-range-start: 3500
      exceptions-active: true
      watched-custom-services:
      - com.ericwyles.chaosengineeringdemo.alphavantage.AlphaVantageService.getPrice
