alphavantage:
  url: http://localhost:9090

worldtradingdata:
  url: https://api.worldtradingdata.com

resilience4j.circuitbreaker:
  instances:
    stockPriceCircuitBreaker:
      minimumNumberOfCalls: 5
      registerHealthIndicator: true
      failureRateThreshold: 50
      waitDurationInOpenState: 60000
      slidingWindowSize: 20
      slidingWindowMinimumNumberOfCalls: 5
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 5